#----------------------------------------------------
# This file is consumed by the --slack-config-filename
# argument. Here you define one or more alert configs
# each separate alert identified another YAML array element
#----------------------------------------------------

- name: "Deployment Result"  # the name of the alert

  # OPTIONAL: Jinja2 template that if provided must return:
  # - 1 (alert will execute)
  # - 0 (alert will NOT execute)
  #
  # For example, You could use this to only fire alerts on failures
  alert_condition: "{{ '1' if not overall_result else '1' }}" # here we fire no matter what

  # Leverages a webhook url.
  # Example hook posts to: https://bitsofinfo.slack.com/messages/CE46Z3TJA/
  # the #bitsofinfo-dev channel
  webhook_url: https://hooks.slack.com/services/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

  # Jinja2 template that is provided a `context` object
  # who has a structure you can see in the below file:
  # https://github.com/bitsofinfo/kubernetes-helm-healthcheck-hook/blob/master/example/slack-jinja2-context.json
  #
  # You can reference any variables in
  # this object in your template. Your template should return a JSON
  # document for a Slack Incoming webhook POST body:
  # https://api.slack.com/incoming-webhooks
  template: >
    {
      "text":"*Deployment result: {{ target_root_url }}*",
      "attachments": [
          {
            "color": "{{ 'good' if overall_result else 'danger' }}",
            "fields": [
              {
                "title":"Check name",
                "value":"{{ check_name }}",
                "short":true
              },
              {
                "title":"Healthcheck result",
                "value":"{{ overall_result }}",
                "short":true
              }
            ]
          }

          {% for check in checks %}
            ,{
              "color": "{{ 'good' if check.result.success else 'danger' }}",
              "fields": [
                {
                  "title":"Url",
                  "value":"{{ check.method }} {{ check.url }}",
                  "short":true
                },
                {
                  "title":"Success?",
                  "value":"{{ check.result.success }} {{ check.result.code }}",
                  "short":true
                }
              ]
            }
        {% endfor %}
      ]
    }

- name: "Failure only alert"  # the name of the alert
  alert_condition: "{{ '1' if not overall_result else '0' }}" # here we fire only on failures
  webhook_url: https://hooks.slack.com/services/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
  template: >
    {
      "text":"*Failure only alert: {{ target_root_url }}*",
      "attachments": [
          {
            "fields": [
              {
                "title":"Healthcheck result",
                "value":"{{ overall_result }}",
                "short":true
              }
            ]
          }
      ]
    }
